add scrollbar for LazyVerticalGrid
nanihadesuka/LazyColumnScrollbar pull request #25
Opened 2023-11-02 06:13 UTC by walt-zhong

add scrollbar for lazyVerticalGrid.any questions,contact me please!!

2023-11-02 13:25 UTC, nanihadesuka commented on lib/src/main/java/my/nanihadesuka/compose/LazyGridVerticalScrollbar.kt
> + */
delete this please

2023-11-02 13:27 UTC, nanihadesuka requested changes
@walt-zhong PR looks good.

For approval the PR needs UI unit tests for the lazy grid scrollbar. You can create a new unit test file with all the cases of the lazy list and add the special ones for the grid list you feel are appropriate.

2023-11-06 07:46 UTC, walt-zhong commented on lib/src/main/java/my/nanihadesuka/compose/LazyGridVerticalScrollbar.kt
> + */
ok

2023-11-06 08:14 UTC, walt-zhong commented
I will create a new one pr

2023-11-06 08:14 UTC, closed without merging